# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=50)),
                ('bucket_creation_date', models.CharField(blank=True, default='', max_length=30)),
                ('change', models.CharField(max_length=25)),
                ('dry_run', models.BooleanField(default=True)),
                ('http_status_code', models.IntegerField(blank=True, default=0)),
                ('location', models.CharField(blank=True, default='', max_length=50)),
                ('new_bucket', models.CharField(blank=True, default='unknown', max_length=10)),
                ('request_created', models.DateTimeField(auto_now_add=True)),
                ('request_modified', models.DateTimeField(auto_now=True)),
                ('response_string', models.CharField(blank=True, default='', max_length=255)),
                ('s3_error', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='Pending', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('breed', models.CharField(max_length=25, unique=True)),
                ('year_discovered', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='RainbowColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=25, unique=True)),
                ('year_discovered', models.CharField(max_length=4)),
            ],
        ),
    ]
